TARGET = ima_adpcm_demo

NUCLEI_SDK_ROOT ?= ../../../..

CORE ?= n300

ARCH_EXT ?=

SRCDIRS = . src data

INCDIRS = . src inc data

COMMON_FLAGS := -O3

LDLIBS = -lm

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
