TARGET = amrwb_dec

NUCLEI_SDK_ROOT ?= ../../../..

SRCDIRS = . src

INCDIRS = . inc src ../data

STDCLIB ?= newlib_full

COMMON_FLAGS := -O3

APP_CXXFLAGS += -std=c++11

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
