TARGET = helix_demo

NUCLEI_SDK_ROOT ?= ../../../..

SRCDIRS = . src data src/libhelix src/libhelix/real 

INCDIRS = . src data src/libhelix/real src/libhelix/pub

STDCLIB ?= newlib_small

COMMON_FLAGS := -O3

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
