TARGET := evrc_demo

NUCLEI_SDK_ROOT ?= ../../../..

SRCDIRS = . code dspmath data

INCDIRS = . include dspmath

STDCLIB ?= newlib_small

COMMON_FLAGS := -O3

LDLIBS += -lm

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base

