TARGET = evs_demo

NUCLEI_SDK_ROOT ?= ../../../..

SRCDIRS = . basic_math basic_op data lib_com lib_dec lib_enc

INCDIRS = . basic_math basic_op lib_com lib_dec lib_enc

STDCLIB ?= newlib_small

COMMON_FLAGS := -O3

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
