TARGET = amrnb_demo

NUCLEI_SDK_ROOT ?= ../../../..

SRCDIRS = . enc/src dec/src data common/src

INCDIRS = . enc/src dec/src enc/include dec/include data common/include oscl

STDCLIB ?= newlib_small

COMMON_FLAGS := -O2

CXXFLAGS += -std=c++11

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
